version: '3'
services:
  db:
    image: postgres:9
    ports:
      - "5432:5432"
  cache:
    image: memcached
    ports:
      - "11211:11211"
  search:
    image: elasticsearch:5
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
