name: Docker
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Docker build (and optional push)
    runs-on: ubuntu-18.04
    env:
      RUBYGEMS_VERSION: 3.1.5
      RUBY_VERSION: 2.7.2
    steps:
    - uses: actions/checkout@v2
    - name: Install themis
        run: |
          sudo apt-get update && sudo apt-get install -y \
                     build-essential git curl lsb-release \
                     apt-transport-https \
              && curl -sL https://pkgs.cossacklabs.com/gpg | apt-key add - \
              && echo "deb https://pkgs.cossacklabs.com/stable/debian echo $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/cossacklabs.list \
              && sudo apt-get update && sudo apt-get install -y libthemis \
              && sudo apt-get -y autoremove && apt-get -y clean \
              && sudo rm -rf /var/lib/apt/lists/*
    - name: Install and start services (needed for image test)
      run: docker-compose up -d
    - name: build, test and optionally push docker image
      run: ./script/build_docker.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

