name: Lint
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install themis
        run: |
          sudo apt-get update && sudo apt-get install -y \
                     build-essential git curl lsb-release \
                     apt-transport-https \
              && curl -sL https://pkgs.cossacklabs.com/gpg | apt-key add - \
              && echo "deb https://pkgs.cossacklabs.com/stable/debian echo $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/cossacklabs.list \
              && sudo apt-get update && sudo apt-get install -y libthemis \
              && sudo apt-get -y autoremove && apt-get -y clean \
              && sudo rm -rf /var/lib/apt/lists/*
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop
  brakeman:
    name: Brakeman
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Brakeman
      run: bundle exec brakeman
