name: Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rails:
    strategy:
      fail-fast: false
      matrix:
        rubygems_version: ['3.1.5', 'latest']
        ruby_version: ['2.7.2']
    name: Rails tests (Ruby ${{ matrix.ruby_version }}, RubyGems ${{ matrix.rubygems_version }})
    runs-on: ubuntu-18.04
    env:
      RUBYGEMS_VERSION: ${{ matrix.rubygems_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install themis
      run: |
       sudo apt-get update && sudo apt-get install -y \
                  build-essential git curl lsb-release \
                  apt-transport-https \
           && curl -sL https://pkgs.cossacklabs.com/gpg | apt-key add - \
           && echo "deb https://pkgs.cossacklabs.com/stable/debian echo $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/cossacklabs.list \
           && sudo apt-get update && sudo apt-get install -y libthemis \
           && sudo apt-get -y autoremove && apt-get -y clean \
           && sudo rm -rf /var/lib/apt/lists/*
    - name: Install and start services
      run: |
        ./script/install_toxiproxy.sh
        docker-compose up -d
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Prepare environment
      run: |
        cp config/database.yml.example config/database.yml
        bundle exec rake db:setup
    - name: Tests
      run: bin/rails test
